//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indiceringsmodule.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Indiceringsmodule.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADA Code.
        /// </summary>
        public static string ADACode {
            get {
                return ResourceManager.GetString("ADACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Names.
        /// </summary>
        public static string AddlNames {
            get {
                return ResourceManager.GetString("AddlNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chattel.
        /// </summary>
        public static string Chattel {
            get {
                return ResourceManager.GetString("Chattel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Fact.
        /// </summary>
        public static string CreateFact {
            get {
                return ResourceManager.GetString("CreateFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Fact Member.
        /// </summary>
        public static string CreateFactMember {
            get {
                return ResourceManager.GetString("CreateFactMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation or Title.
        /// </summary>
        public static string DesignationOrTitle {
            get {
                return ResourceManager.GetString("DesignationOrTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact with ID {0} was missing a link named &apos;{1}&apos;. It was recreated at the end of the document..
        /// </summary>
        public static string DictHasMessage1 {
            get {
                return ResourceManager.GetString("DictHasMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to several facts are missing their links: {0}..
        /// </summary>
        public static string DictHasMessage2 {
            get {
                return ResourceManager.GetString("DictHasMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Context.
        /// </summary>
        public static string DocumentContext {
            get {
                return ResourceManager.GetString("DocumentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link(s) named {0} appear(s) more than once..
        /// </summary>
        public static string DuplicatesMessage {
            get {
                return ResourceManager.GetString("DuplicatesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Document Settings.
        /// </summary>
        public static string EditDocSettings {
            get {
                return ResourceManager.GetString("EditDocSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact.
        /// </summary>
        public static string Fact {
            get {
                return ResourceManager.GetString("Fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Member.
        /// </summary>
        public static string FactMember {
            get {
                return ResourceManager.GetString("FactMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Subtype.
        /// </summary>
        public static string FactSubType {
            get {
                return ResourceManager.GetString("FactSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fact Type.
        /// </summary>
        public static string FactType {
            get {
                return ResourceManager.GetString("FactType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The link: &apos;{0}&apos; in fact number: {1} is not paired to any fact member. please remove it..
        /// </summary>
        public static string ListHasMessage1 {
            get {
                return ResourceManager.GetString("ListHasMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to several links are not paired to fact members: {0}. Please remove these..
        /// </summary>
        public static string ListHasMessage2 {
            get {
                return ResourceManager.GetString("ListHasMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Code.
        /// </summary>
        public static string LocationCode {
            get {
                return ResourceManager.GetString("LocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink &apos;{0}&apos; in fact {1} does not match up with any fact member..
        /// </summary>
        public static string MismatchMessage1 {
            get {
                return ResourceManager.GetString("MismatchMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following hyperlinks do not match up to any fact members: {0}..
        /// </summary>
        public static string MismatchMessage2 {
            get {
                return ResourceManager.GetString("MismatchMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Municipality.
        /// </summary>
        public static string Municipality {
            get {
                return ResourceManager.GetString("Municipality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Fact.
        /// </summary>
        public static string NextFact {
            get {
                return ResourceManager.GetString("NextFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Image Selected.
        /// </summary>
        public static string NoImageSelected {
            get {
                return ResourceManager.GetString("NoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle.
        /// </summary>
        public static string Particle {
            get {
                return ResourceManager.GetString("Particle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Fact.
        /// </summary>
        public static string PreviousFact {
            get {
                return ResourceManager.GetString("PreviousFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate.
        /// </summary>
        public static string RealEstate {
            get {
                return ResourceManager.GetString("RealEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored Hyperlink: .
        /// </summary>
        public static string RestoredHyperlink {
            get {
                return ResourceManager.GetString("RestoredHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source ID.
        /// </summary>
        public static string SourceID {
            get {
                return ResourceManager.GetString("SourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Type.
        /// </summary>
        public static string SourceType {
            get {
                return ResourceManager.GetString("SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toponym.
        /// </summary>
        public static string Toponym {
            get {
                return ResourceManager.GetString("Toponym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcription.
        /// </summary>
        public static string Transcription {
            get {
                return ResourceManager.GetString("Transcription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worth.
        /// </summary>
        public static string Worth {
            get {
                return ResourceManager.GetString("Worth", resourceCulture);
            }
        }
    }
}
